# Generated by Django 4.0.1 on 2022-01-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=4)),
                ('project_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fixing',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.category')),
                ('fixing_type', models.TextField()),
                ('metric_size', models.CharField(choices=[('M4', 'M4'), ('M6', 'M6'), ('M8', 'M8'), ('M10', 'M10'), ('M12', 'M12')], max_length=5)),
                ('metric_length', models.IntegerField()),
            ],
            bases=('parts.category',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=15)),
                ('part_title', models.CharField(max_length=255)),
                ('part_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='parts.category')),
                ('part_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='parts.project')),
            ],
        ),
    ]
